### ISSUE TITLE
Could not read WebJar RequireJS config for: regression-js 1.3.0

### ISSUE THREAD

**Issue by amaury-d** [webjars/regression-js#1]
Hello,

> 2016-05-10 12:45:40,229 WARN  [http-bio-8080-exec-4] webjars.RequireJS (RequireJS.java:355) - Could not read WebJar RequireJS config for: regression-js 1.3.0

The requirejs config file should be added.

Best regards.

**Comment by jamesward** [comment]
This will be released shortly as `1.3.0-1`.

**Comment by amaury-d** [comment]
Thanks!

On Tue, May 10, 2016 at 5:00 PM, James Ward notifications@github.com
wrote:

> This will be released shortly as 1.3.0-1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/webjars/regression-js/issues/1#issuecomment-218185196

## 

Amaury Decrême
